export const userTypes = {
    CREATE_USER: "CREATE_USER",
    LOGGIN_USER: "LOGGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
};

export const restaurantsTypes = {
  RESTAURANT_GET: 'RESTAURANT_GET',
  RESTAURANT_SELECTED: 'RESTAURANT_SELECTED',
  SEARCH_RESTAURANTS: 'SEARCH_RESTAURANTS',
  GET_RESTAURANT_DISHES: "GET_RESTAURANT_DISHES",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART"
}
export const platosTypes = {
  PLATOS_GET: 'PLATOS_GET',
  PLATOSRESTAURANTE_GET: 'PLATOSRESTAURANTE_GET' 
}
export const buttonsTypes = {
  BUTTON__GET: 'BUTTON__GET',
}