export const userTypes = {
    CREATE_USER: "CREATE_USER",
    LOGGIN_USER: "LOGGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
};

export const restaurantsTypes = {
  RESTAURANT_GET: 'RESTAURANT_GET',
  RESTAURANT_ADD: 'RESTAURANT_ADD',
  RESTAURANT_FILTERED: 'RESTAURANT_FILTERED',
  RESTAURANT_SELECTED: 'RESTAURANT_SELECTED'
}
export const platosTypes = {
  PLATOS_GET: 'PLATOS_GET',
  PLATOSRESTAURANTE_GET: 'PLATOSRESTAURANTE_GET' 
}
export const buttonsTypes = {
  BUTTON__GET: 'BUTTON__GET',
}